import { useState } from "react";
import OtpInput from "react-otp-input";
import { useMutation } from "react-query";
import { useNavigate } from "react-router-dom";
import baseAxios from "../../config/axios";

const TwoFactor = ({ email }: { email: string }) => {
  const navigate = useNavigate();
  const { mutateAsync } = useMutation("otp", (data: any) =>
    baseAxios.post("/auth/2fa/verify", data)
  );
  const [otp, setOtp] = useState("");

  const verifyOtp = () => {
    mutateAsync({ email, code: otp }).then((res) => {
      if (res.status === 201) {
        localStorage.setItem("accessToken", res.data.accessToken);
        navigate("/landing");
      }
    });
  };

  return (
    <div className="fixed top-0 left-0 w-full h-full bg-black bg-opacity-50 flex justify-center items-center">
      <div className="w-[600px] mx-auto bg-white py-20 px-20">
        <p className="text-2xl mb-10 text-center">
          Please Enter the One Time Password(OTP) generated by your Microsoft
          Authenticator App.
        </p>
        <OtpInput
          value={otp}
          onChange={setOtp}
          numInputs={6}
          renderSeparator={false}
          containerStyle={{ gap: "20px", justifyContent: "center" }}
          renderInput={(props) => (
            <input
              {...props}
              style={{ width: "50px", height: "50px" }}
              className="border border-main w- text-center text-4xl rounded-md"
            />
          )}
        />

        <button
          onClick={verifyOtp}
          className="bg-main text-white py-3 px-20 rounded-md mt-5 mx-auto block text-2xl hover:bg-green-700 transition"
        >
          Verify
        </button>
      </div>
    </div>
  );
};

export default TwoFactor;
