import { FC, useState } from "react";
import OtpInput from "react-otp-input";

interface IProps {
  callback: (otp: string) => void;
}
const TwoFactor: FC<IProps> = ({ callback }) => {
  const [otp, setOtp] = useState("");

  return (
    <div className="fixed top-0 left-0 w-full h-full bg-black bg-opacity-50 flex justify-center items-center">
      <div className="w-[600px] mx-auto bg-white py-20 px-20">
        <p className="text-2xl mb-10 text-center">
          Please Enter the One Time Password(OTP) generated by your Microsoft
          Authenticator App.
        </p>
        <OtpInput
          value={otp}
          onChange={setOtp}
          numInputs={6}
          renderSeparator={false}
          containerStyle={{ gap: "20px", justifyContent: "center" }}
          renderInput={(props) => (
            <input
              {...props}
              style={{ width: "50px", height: "50px" }}
              className="border border-main w- text-center text-4xl rounded-md"
            />
          )}
        />

        <button
          onClick={() => callback(otp)}
          className="bg-main text-white py-3 px-20 rounded-md mt-5 mx-auto block text-2xl hover:bg-green-700 transition"
        >
          Verify
        </button>
      </div>
    </div>
  );
};

export default TwoFactor;
